"""empty message

Revision ID: a6e6373f16f5
Revises: 
Create Date: 2019-07-27 00:43:01.894761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e6373f16f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'driver_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('driver', 'name_slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'driver', ['name_slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='unique')
    op.alter_column('driver', 'name_slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('driver', 'driver_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
